discordBotToken: ""
discordBotClientID: ""
channels:
  logs: ""
colours:
  success: ""
  failure: ""
  warning: ""
  blurple: ""
  clear: ""
emojis:
  success: ""
  error: ""
  warning: ""
  arrow: ""
  dash: ""
  info: ""
  staff: ""
  developer: ""
  banned: ""
  bot: ""
  join: ""
  leave: ""
  link: ""